
version: '3'

networks:
  impacta:
    driver: bridge

services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    restart: always
    networks:
      - impacta
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=impacta
      - MYSQL_TCP_PORT=3306
  nginx:
    container_name: nginx
    image: nginx:latest
    links:
      - mysqldb:mysqldb
    ports:
      - "80:80"
    depends_on:
      - mysqldb